columns:
  date:
    type: datetime
    description: "Date of the measurement"
  aqi:
    type: float
    description: "Air Quality Index"
  pm10:
    type: float
    description: "Particulate matter 10 micrometers or less in diameter"
  pm25:
    type: float
    description: "Particulate matter 2.5 micrometers or less in diameter"
  no2:
    type: float
    description: "Nitrogen dioxide concentration"
  o3:
    type: float
    description: "Ozone concentration"
  so2:
    type: float
    description: "Sulfur dioxide concentration"
  co:
    type: float
    description: "Carbon monoxide concentration"