artifacts_root: artifacts

data_ingestion:
  type: local
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/Abdelm4lek/Datasets/raw/refs/heads/main/Paris_daily_air_quality.zip
  local_data_file: artifacts/data_ingestion/Paris_daily_air_quality.zip
  unzip_dir: artifacts/data_ingestion
