artifacts_root: artifacts

data_ingestion:
  mode: production  # local or production
  
  # Local development configuration
  local:
  root_dir: artifacts/data_ingestion
  source_url: https://raw.githubusercontent.com/Abdelm4lek/Datasets/main/Velib_historique_stations.rar
  local_data_file: artifacts/data_ingestion/velib_data.rar
  unzip_dir: artifacts/data_ingestion
  unzip_data_path: artifacts/data_ingestion/historique_stations.csv
  
  # Production configuration  
  production:
    root_dir: artifacts/data_ingestion
    unzip_data_path: artifacts/data_ingestion/fresh_data.csv
    training_window_days: 30
    min_data_points: 10000


data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/fresh_data.csv
  STATUS_FILE: artifacts/data_validation/status.txt


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/fresh_data.csv
  

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib
  mlflow_uri: "https://dagshub.com/Abdelm4lek/End-to-end-ML-project-with-MLflow.mlflow"

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json
  target_column: "nbvelosdispo"
  mlflow_uri: "https://dagshub.com/Abdelm4lek/End-to-end-ML-project-with-MLflow.mlflow"

prediction:
  root_dir: artifacts/predictions
  model_path: artifacts/model_trainer/model.joblib
  prediction_window_hours: 24
  min_data_points: 24
  prediction_interval_minutes: 60
  predictions_path: artifacts/predictions/station_predictions.csv