artifacts_root: artifacts

data_ingestion:
  type: local
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/lovasoa/historique-velib-opendata/releases/download/new/stations.zip
  local_data_file: artifacts/data_ingestion/bike_stations.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/historique_stations.csv
  STATUS_FILE: artifacts/data_validation/status.txt


